version: "3"

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-server
    depends_on:
      - postgresql
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - ./data/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube_extensions:/opt/sonarqube/extensions
      - ./data/sonarqube_logs:/opt/sonarqube/logs

  postgresql:
    image: postgres:12
    container_name: sonarqube-database
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./data/postgresql_data:/var/lib/postgresql/data
